version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./init/01-cleanup.sql:/docker-entrypoint-initdb.d/01-cleanup.sql
      - ./init/02-init.sql:/docker-entrypoint-initdb.d/02-init.sql
      - ./init/03-test-data.sql:/docker-entrypoint-initdb.d/03-test-data.sql
networks:
  default:
    driver: bridge